export const API_CALL_REQUEST_USER_ONE = 'API_CALL_REQUEST_USER_ONE';
export const API_CALL_REQUEST_USER_TWO = 'API_CALL_REQUEST_USER_TWO';
export const API_CALL_FAILURE = 'API_CALL_FAILURE';
export const TWEETS_USER_ONE = 'TWEETS_USER_ONE';
export const TWEETS_USER_TWO = 'TWEETS_USER_TWO';
